#!/bin/bash
lf=/tmp/SBuilderClientLock
dpath=`dirname ${0}`
echo $dpath
##
case $1 in
start)
 echo running SyncBuilder.
 $dpath/SyncBuilder $lf -C -c $dpath/Demoes.cfg -l $dpath/log.conf
;;
stop)
 echo "stopping SyncBuilder."
 $dpath/SyncBuilder $lf stop
;;
esac

