CREATE TABLE IF NOT EXISTS FINFO(
 CWD VARCHAR(255),
 LOCATION INT,
 PARENT VARCHAR(255),
 MTIME VARCHAR(20) NOT NULL,
 NAME VARCHAR(255) NOT NULL,
 TYPE INT NOT NULL,
 SIZE VARCHAR(20) NOT NULL,
 STATE INT NOT NULL,
 PRIMARY KEY(CWD, LOCATION)
)
 
 