#!/bin/bash
lf=/tmp/SBuilderClientLock
dpath=`dirname ${0}`
cfg=/etc/sbuilder
##
case $1 in
start)
 echo running SyncBuilder.
 $dpath/SyncBuilder $lf -C -c $cfg/Demoes.cfg -l $cfg/log.conf
;;
stop)
 echo "stopping SyncBuilder."
 $dpath/SyncBuilder $lf stop
;;
esac

